print("Importing contants...")

#Size of Grid and objects in the grid
MULTIPLIER = 7
WINDOWSIZE = 81
WINDOWWIDTH = WINDOWSIZE * MULTIPLIER
WINDOWHEIGHT = WINDOWSIZE * MULTIPLIER
BOXSIZE = WINDOWSIZE * MULTIPLIER / 3
CELLSIZE = BOXSIZE / 3
NOTESIZE = CELLSIZE / 3

#Colors
WHITE    =(255,255,255)
BLACK    =(  0,  0,  0)
GREY     =(220,220,220)

print("Finished")
